### ISSUE TITLE
Integrate CI

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#1]
We should incorporate CI tests on each pull request. If we go with [Cloud Build](https://cloud.google.com/cloud-build/), we should be able to easily hook into things like cloud storage to host generated files.

**Comment by chrisfrederickson** [comment]
@Fleker How does Cloud Build work with open source projects? I have only ever used it for private work. Can you set it up so that everyone can see the build results?

**Comment by Fleker** [comment]
I need to see, as there are some non-trivial configurations to enable it for this org.
