### ISSUE TITLE
Kubos logic has `return`, but the return type is void

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#114]
We should update whatever the value of `val` is to the thing we are supposed to return, rather than return directly.

**Comment by mandrin17299** [comment]
I would like to take this up. Could you please help me get started? Thanks!

**Comment by Fleker** [comment]
On [line 179](https://github.com/google/cyanobyte/blob/master/templates/kubos.c#L179) of `kubos.c`, the auto-generated function has `void` as the return type.

Later on, the return value appears to be explicitly returned on [line 199](https://github.com/google/cyanobyte/blob/master/templates/kubos.c#L199) and [line 203](https://github.com/google/cyanobyte/blob/master/templates/kubos.c#L203). This return statement is poorly placed, as it shouldn't be a direct return. Rather, we should reassign the value of our pointer `val`, which is defined in the function header.

**Comment by mandrin17299** [comment]
Hey @Fleker , is this the change that was required?
![googleos](https://user-images.githubusercontent.com/29328350/70865937-17e3b100-1f89-11ea-9686-0dc87dec4684.png)

**Comment by Fleker** [comment]
Yes @PranshuPanwar that would be the correct fix to the issue. You may need to rebase on top of a few larger changes.
