### ISSUE TITLE
Python docstring format

### ISSUE THREAD

**Issue by chrisfrederickson** [google/cyanobyte#16]
We should standardize the python docstring format (and other style-related things). Thoughts on which type to use?

**Comment by Fleker** [comment]
Google's Python style guide: http://google.github.io/styleguide/pyguide.html#381-docstrings

**Comment by chrisfrederickson** [comment]
Sounds good. The current docstrings should be updated to reflect that.

**Comment by Fleker** [comment]
I will need a way to pad the strings
