### ISSUE TITLE
Replace getopt parsing with argparse

### ISSUE THREAD

**Issue by chrisfrederickson** [google/cyanobyte#19]
Alright, this is more of a preference and don't really care if we make this change or not. I just find argparse easier to look at.

https://docs.python.org/3/library/argparse.html

**Comment by Fleker** [comment]
In the past I've also used [click](https://click.palletsprojects.com/en/7.x/).

**Comment by chrisfrederickson** [comment]
Ooo, that looks quite nice. I guess the only downside is the dependency on a non-standard library package. But it is probably worth it given most people will use this project on the command line.
