### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#203]
The project was recently mentioned in an [Adafruit newsletter](https://blog.adafruit.com/2020/04/29/icymi-python-on-microcontrollers-micropython-turns-7-circuitpython-5-3-0-rc0-is-out-and-more-python-adafruit-circuitpython-icymi-circuitpython-micropython-thepsf/) with a diagram from [the website](https://cyanobyte.dev). The header image was the diagram rather than a more useful logo.

**Comment by urish** [comment]
Congratulations for the mention!

Do you need some help with the logo, Nick?

**Comment by Fleker** [comment]
I've done minor graphic design in the past, but I'm open to ideas here.

**Comment by urish** [comment]
Do you have some general idea of what the logo should symbolize?

**Comment by Fleker** [comment]
No I'm not really sure that it should be. The name is a combination of "cyanoprint" and a digital "byte", but how would that translate into a logo?

**Comment by urish** [comment]
Google images mostly brings leaves for cyanoprints:

![image](https://user-images.githubusercontent.com/892318/80744464-5ee0d600-8b27-11ea-9b46-e8e99553f27a.png)

So perhaps some kind of leaf in 8-bit pixelated style?

**Comment by Fleker** [comment]
Like some sort of digital leaf?

**Comment by urish** [comment]
Yeah!

**Comment by Fleker** [comment]
![cyan1](https://user-images.githubusercontent.com/3291635/80922151-1acd1b80-8d49-11ea-9216-1d331e278545.png)

Here's my first attempt. I'm still not sure about the design of the peripherals.

**Comment by urish** [comment]
Yes, the small details are lost when the logo is turned into a thumbnail:

![image](https://user-images.githubusercontent.com/892318/80924241-78388b00-8d90-11ea-9524-b13344cb0e5a.png)

If you decide to keep the peripherals, I'd probably add one or two more, and break the symmetry (maybe also use a different shape for each, rectangle, triangle, circle, etc.). In the current configuration they resemble hands

**Comment by Fleker** [comment]
Swapped it up a little more to emphasize the leaf with minimal wiring
![cyan2](https://user-images.githubusercontent.com/3291635/81351692-ed5ad780-9092-11ea-915d-20eccb3d6dab.png)
![cyan2 32](https://user-images.githubusercontent.com/3291635/81351719-f9469980-9092-11ea-98d1-07cc1385ef05.png)

**Comment by urish** [comment]
Can you also try without the rectangle? I think it'll improve the contrast of the logo against its background

**Comment by Fleker** [comment]
Removing the background

![cyan4](https://user-images.githubusercontent.com/3291635/81480623-d930ea80-91f8-11ea-9214-e2e25910990e.png)
![cyan432](https://user-images.githubusercontent.com/3291635/81480624-d9c98100-91f8-11ea-9026-07507586e947.png)

**Comment by Fleker** [comment]
Change in cable direction

![cyan3](https://user-images.githubusercontent.com/3291635/81480630-e0f08f00-91f8-11ea-9396-f7c3377523f3.png)
![cyan332](https://user-images.githubusercontent.com/3291635/81480631-e0f08f00-91f8-11ea-9375-2ec7652ebdc9.png)
