### ISSUE TITLE
Add copyright year to spec info

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#23]
To do the generation of copyright headers, one needs to know both the copyright owner and the year of the copyright. Both can be represented as strings that we plop right into the header, as shown in #20.

**Comment by chrisfrederickson** [comment]
Should that be an entirely separate block in the yaml?

```yaml
info:
    copyright:
        year: 2019
        company: Example, Inc.
```

**Comment by Fleker** [comment]
Would we want to share the same info as the info.contact field?

**Comment by chrisfrederickson** [comment]
Depends on how verbose we want to be. Are there cases where the copyright owner would be different from the maintainer or whoever the point of contact is?

**Comment by Fleker** [comment]
It depends. Would we expect an individual to "own" a device spec, while the copyright ownership is the company?
