### ISSUE TITLE
Add BLE?

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#24]
Should we add wireless specs such as BLE as goals for communication protocols in the spec?

**Comment by chrisfrederickson** [comment]
I would say it should be a long term goal. Not sure how exactly it would work out, but definitely worth further thought down the line.

**Comment by Fleker** [comment]
Support for BLE and other wireless transport layers are a good idea. However, the project will be focusing on wired serial-like transports for now such as I2C and UART.
