### ISSUE TITLE
BMP280 Generated files for Arduino with the given datasheet is not working?

### ISSUE THREAD

**Issue by rohitsam** [google/cyanobyte#244]
Hey, 

I have run cyanobyte-Codegen for Sensor BMP280 and generated code for Arduino.

> cyanobyte-codegen -t templates/arduino.cpp -o ./build peripherals/BMP280.yaml

> cyanobyte-codegen -t templates/arduino.h -o ./build peripherals/BMP280.yaml

Later I have used these generated library files and written these lines of code for Atmega 328(Arduino) 
```
#include "BMP280.h"
TwoWire Wire1;
BMP280 sensor(Wire1);

void setup() {
sensor.begin();
Serial.begin(9600);
}
void loop() {
Serial.println(sensor.temperatureasCelsius());
delay(2000);
}
```

But I get null output.
I have also confirmed my  my hardware to be working fine, since I have verifyed it with [adfruits library ](https://github.com/adafruit/Adafruit_BMP280_Library)

**Comment by rohitsam** [comment]
In the cyanobyte datasheet Many registers are given wrong datasize #246

**Comment by rohitsam** [comment]
```
uint16_t BMP280::readDigP8() {
    uint8_t datum;
    uint16_t value;
    _wire->beginTransmission(DEVICE_ADDRESS);
    _wire->write(REGISTER_DIGP8);
    if (_wire->endTransmission(false) != 0) {
        return -1;
    }

    if (_wire->requestFrom(DEVICE_ADDRESS, 2) != 2) {
        return 0;
    }

    datum = _wire->read();
    value = value << 8 | datum;
    datum = _wire->read();
    value = value << 8 | datum;

    return value;
}
```
This is the generated code of BMP280 for arduino, and  the **endianness** is ignored.
![image](https://user-images.githubusercontent.com/16455716/95298132-36f55b80-0899-11eb-844a-9ea11d31257a.png)

**Comment by Fleker** [comment]
Yeah I'll need to re-review the datasheet and ensure that the registers are all correctly typed.

**Comment by rohitsam** [comment]
The template for Arduino doesn't have method to typecast variables.

**Comment by Fleker** [comment]
Arduino variables should now be properly signed as-necessary.
