### ISSUE TITLE
Should registers be contained within the I2C block?

### ISSUE THREAD

**Issue by chrisfrederickson** [google/cyanobyte#26]
Should registers be contained within the I2C block instead of at the same level? This may make more sense when we support more communication protocols.

**Comment by Fleker** [comment]
Would an i2c register be formatted notably different from a SPI register? Is there an instance where a device could support two communication protocols, and create a conflict in knowing how to control registers?

**Comment by chrisfrederickson** [comment]
I suppose the other question is, are there chips with multiple serial buses?

**Comment by Fleker** [comment]
I've seen occasionally devices that can support one, but allow you to switch, like [this Adafruit I2C/SPI LED Backpack](https://www.adafruit.com/product/292).

I suppose if your target is a microcontroller, you would want to support multiple busses. But then would we want to support more than one i2c bus?

**Comment by Fleker** [comment]
In some applications, having more than one i2c bus could be beneficial for redundancy (if one bus gets damaged it can use the backup).

**Comment by Fleker** [comment]
Let's keep registers as a separate data model which could be used in different scenarios.
