### ISSUE TITLE
Support for template directories

### ISSUE THREAD

**Issue by chrisfrederickson** [google/cyanobyte#34]
As the templates increase in complexity, they will almost certainly be comprised of multiple files that will always be used together. We should allow the user to pass in a template directory.

Eventually, do we want to have a set of builtin templates that are referenced by name (e.g. `python` instead of a path to a directory)?

**Comment by Fleker** [comment]
Yeah at some point we should have some sort of enum or easy redirect system. In Protobufs, for example, plugins can be specified like:

`protoc --cyanobyte_out=./build foo.proto bar.proto`

This would end up looking for the binary `protoc-gen-cyanobyte`.

While we may need to use multiple template files in the background, I'm not sure we need to pass in a directory as an argument. Jinja allows you to import other files into a base file, so we could have a barebones `templates/raspberrypi.py` file that loads in `templatates/raspberrypi/module1.py` on-demand.

**Comment by Fleker** [comment]
Handled by #164.
