### ISSUE TITLE
Git presubmit linter

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#46]
Optionally add [additional tools](https://github.com/Fleker/actions-on-google-nodejs/blob/master/cloudbuild.yaml) from the [Git Presubmit Linter project](https://github.com/google/git-presubmit-linter) to the Cloud Build configuration for additional verification of the source code and generation of resources such as changelogs.

**Comment by chrisfrederickson** [comment]
Neat. I'm all for adding more linters that improve the quality of the project. 👍

**Comment by Fleker** [comment]
Mark as infeasible as Google Cloud Build does not use a standard git environment in its CI envrionment.
