### ISSUE TITLE
Add CI task to check dependency licenses?

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#49]
We can create a Cloud Build configuration which only gets triggered when the `requirements.txt` is changed, to check the license for each one to verify that they are good OSS licenses like _MIT_ or _Apache-2.0_. This can be through a [shell script](https://github.com/google/git-presubmit-linter#spdx-licenses).

Should we add this extra CI task, or is it not worth the time?

**Comment by chrisfrederickson** [comment]
I'd just recommend enabling PyUP as it is free for open source projects and has this capability. https://pyup.io/

**Comment by Fleker** [comment]
Mark as infeasible.
