### ISSUE TITLE
Spec validator tool

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#7]
There should be a tool that validates possible fields. This could be done as a custom linter, or convert the YAML to JSON as part of the linter and use [JSON Schema](https://json-schema.org/).

Once this happens, we should add CI tests for it and keep it up to date as we make spec changes.

**Comment by chrisfrederickson** [comment]
I get the feeling that converting to JSON and using JSON Schema is going to be far easier to update and maintain.

**Comment by chrisfrederickson** [comment]
I'll take on the initial version of the JSON Schema and validator.
