### ISSUE TITLE
Template enums

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#82]
Provide a specific string instead of a file. Then the codegen tool will redirect to the file.

Instead of `python3 src/codegen.py ... -t templates/raspberrypi.py`

You can do `python3 src/codegen.py ... -t RASPBERRYPI`

This can also be replaced with an array of templates, which may be more useful at tackling templates with several files that need to be generated, like the header and source files of C programs.

**Comment by OlgaCh** [comment]
Hey @Fleker 
May I grab this one for `Hacktoberfest`?

**Comment by Fleker** [comment]
Sure!
