### ISSUE TITLE
Improve peripheral naming consistency

### ISSUE THREAD

**Issue by Fleker** [google/cyanobyte#85]
Right now we have two naming conventions.

* Mcp4725.yaml with name Mcp4725
* MCP9808.yaml with name MCP9808
* Tcs3725.yaml with name TCS3725

We need to pick one and update tests and stuff.

**Comment by tlentali** [comment]
Hey @Fleker, I would like to take this one, may I ?

**Comment by tlentali** [comment]
Is it ok for you is we take the "all uppercase" naming convention ?

**Comment by tlentali** [comment]
I made the PR #88 for this issue

**Comment by Fleker** [comment]
Yeah that's fine.
